import * as fs from "fs";
import Handlebars from "handlebars";

/**
 * Takes a compiled SVG template, replaces the appropriate placeholders, and
 * returns the resulting SVG
 * @param template The compiled template generated by compileSvg()
 * @param replacements The replacments to apply
 * @returns The SVG with the replacements applied
 */
export function generateSvgForSetImage(
  template: ReturnType<typeof compileSvg>,
  replacements: Record<string, unknown>
): string {
  if (!template) {
    return "";
  }

  // Render the SVG content with Handlebars replacements
  const renderedSvg = template(replacements);

  return `data:image/svg+xml;base64,${Buffer.from(renderedSvg, "utf8").toString(
    "base64"
  )}`;
}

/**
 * Compiles an SVG to a Handlebars template
 * @param templatePath The path to the SVG
 * @returns The compiled SVG
 */
export function compileSvg(templatePath: string) {
  let svgContent: string;

  try {
    svgContent = fs.readFileSync(templatePath, "utf8");
  } catch (err) {
    console.error(err);
    return undefined;
  }

  return Handlebars.compile(svgContent);
}
